### PR TITLE
Remove BurntSushi

### PR DESCRIPTION
**Pull request by nebhale**
Previously, this project used the BurntSushi TOML library.  This library is now unmaintained and shouldn't be used for long term projects.  This change migrates the project onto an alternative TOML library.

### CODE REVIEW

**Review by ekcasey — APPROVED** [review]

**Comment by nebhale** [comment]
Agreed to hold this for the next version of `go-toml` with fixes for known quoting issues.

**Comment by samj1912** [comment]
v1.9.0 was just released. Should this be merged now?

**Comment by ekcasey** [comment]
@sclevine was following the bug/issues with go-toml closely, maybe he can give us his take on whether it is ready for primetime?

**Comment by samj1912** [comment]
The other thing to note is that we have different projects using different toml libraries. From what I can see lifecycle uses Burnt Sushi where as pack uses go toml. Similarly libpak (not in CNB but it is used alongside libcnb quite a bit) which consumes libcnb uses go toml. 

Maybe out of scope for this PR but we should also decide on a CNB org level which toml library should we use to avoid duplicate libraries being included. 

cc @buildpacks/platform-maintainers @buildpacks/implementation-maintainers for their thoughts on the usage of these two libraries.

**Comment by ekcasey** [comment]
@samj1912 Since BurntSushi is no longer maintained I think the plan is to switch to go-toml. However, we needed to wait for some bugfixes in go-toml to avoid introducing bugs into our applications

**Comment by samj1912** [comment]
Given that Burnt sushi toml was revived - should we close this?

**Comment by samj1912** [comment]
Closing for now since we merged a bunch of dependabot changes to bump the burnt sushi toml version. Feel free to re-open if we feel strongly about moving to this.

**Pull request closed without merging**
